app = "dancodes"
primary_region = "iad"

[build]

[env]
  XDG_DATA_HOME = "/vol/xdg/data"
  XDG_STATE_HOME = "/vol/xdg/state"
  XDG_CACHE_HOME = "/vol/xdg/cache"
  XDG_CONFIG_HOME = "/vol/xdg/config"
  # Make app.opencode.ai's "Open project" folder picker start in our worktrees dir
  # - This normally uses $HOME, but changing $HOME causes other problems (e.g. XDG dirs, and who knows what else)
  # - HACK So instead we use this undocument $OPENCODE_TEST_HOME var, and if it ever changes then oh well
  #   - https://github.com/anomalyco/opencode/blob/8bf06cb/packages/opencode/src/global/index.ts#L16
  OPENCODE_TEST_HOME = "/vol/projects/worktrees"
  OPENCODE_CONFIG = "/opt/dancodes/opencode.json"
  GITHUB_USER = "jdanbrown"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 80

[[vm]]
  size = "performance-8x"
  memory = "16gb"

[mounts]
  source = "dancodes_vol"
  destination = "/vol"
