#!/usr/bin/env bash
set -eu

function show_cmd() {
  # Use 2>/dev/null with tput to silence this headless error: "tput: No value for $TERM and no -T specified"
  black="$(tput setaf 0 2>/dev/null || true)"
  off="$(tput sgr0 2>/dev/null || true)"
  echo -e "$black\$" "$@" "$off" >&2
  "$@"
}

function isatty() {
  [ -t 1 ]
}

if isatty; then
  DOCKER_OPTS="${DOCKER_OPTS:-} -it"
fi

show_cmd docker run \
    --rm \
    -p 8080:8080 \
    -e AUTH_PASSWORD='dev' \
    -e AUTH_SECRET='dancodes-dev-secret' \
    -e GITHUB_USER="$GITHUB_USER" \
    -e GITHUB_TOKEN="$GITHUB_TOKEN" \
    -e OPENROUTER_API_KEY="$OPENROUTER_API_KEY" \
    -e CONTEXT7_API_KEY="$CONTEXT7_API_KEY" \
    -v /tmp:/tmp \
    -v "$PWD":"$PWD":ro \
    -w "$PWD" \
    ${DOCKER_OPTS:-} \
    'dancodes' \
    "$@"
