#!/usr/bin/env bash
set -eu

function show_cmd() {
  black="$(tput setaf 0 2>/dev/null || true)"
  off="$(tput sgr0 2>/dev/null || true)"
  echo -e "$black\$" "$@" "$off" >&2
  "$@"
}

show_cmd ruff check .
show_cmd ruff format --check .
show_cmd pyright
